# docker-compose.yml (プロジェクトルート直下)
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: rakuten_app
    volumes:
      # プロジェクトルート全体を /var/www/html にマウント
      - ./:/var/www/html:delegated
    ports:
      - "8080:80"
    environment:
      APCU_ENABLE: "yes"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: rakuten_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: rakuten
      MYSQL_USER: rakuten
      MYSQL_PASSWORD: rakutenpass
    ports:
      - "3306:3306"

volumes:
  db_data:
