version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: rakuten_app
    volumes:
      - ./:/var/www/html:delegated
    ports:
      - "8080:80"
    environment:
      # Postgres 向け
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: rakuten
      DB_USERNAME: rakuten
      DB_PASSWORD: rakutenpass
      APPLICATION_ID: dummy    # ローカル動作確認用
      APCU_ENABLE: "yes"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: rakuten_db
    environment:
      POSTGRES_USER: rakuten
      POSTGRES_PASSWORD: rakutenpass
      POSTGRES_DB: rakuten
    ports:
      - "5432:5432"
    volumes:
      - db_data2:/var/lib/postgresql/data

volumes:
  db_data2:
